{
 "title": "Holiday",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stage_names",
    "query": "TitleStage,AvatarSelectionStage,VirtualStage"
   }
  ]
 },
 "panels": [
  {
   "title": "Unique users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(count_over_time({app=\"Holiday\"} | json [$__range])) by (ClientId))"
    }
   ]
  },
  {
   "title": "Top 10 OS",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (OS) (count_over_time({app=\"Holiday\"} | json | UsageId=\"FirstUse\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top 10 Device Type",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (DeviceType) (count_over_time({app=\"Holiday\"} | json | UsageId=\"FirstUse\" [$__range])))"
    }
   ]
  },
  {
   "title": "Top 10 Device Model",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by (DeviceModel) (count_over_time({app=\"Holiday\"} | json | UsageId=\"FirstUse\" [$__range])))"
    }
   ]
  },
  {
   "title": "Stay time (seconds) in $stage_names",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | StayTimeSeconds <= 30 [$__range])) or vector(0)",
     "legendFormat": "0 to 30"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | StayTimeSeconds > 30 | StayTimeSeconds <= 60 [$__range])) or vector(0)",
     "legendFormat": "31 to 60 (1min)"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | StayTimeSeconds > 60 | StayTimeSeconds <= 180 [$__range])) or vector(0)",
     "legendFormat": "61 to 180 (3min)"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | StayTimeSeconds > 180 | StayTimeSeconds <= 360 [$__range])) or vector(0)",
     "legendFormat": "181 to 360 (6min)"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | StayTimeSeconds > 360 | StayTimeSeconds <= 600 [$__range])) or vector(0)",
     "legendFormat": "361 to 600 (10min)"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | StayTimeSeconds > 600 [$__range])) or vector(0)",
     "legendFormat": "601 (10min) or more"
    }
   ]
  },
  {
   "title": "Text Chats Sent (times) in $stage_names",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | NumberOfTextChatsSent = 0 [$__range])) or vector(0)",
     "legendFormat": "0"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | NumberOfTextChatsSent > 0 | NumberOfTextChatsSent <= 5 [$__range])) or vector(0)",
     "legendFormat": "1 to 5"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | NumberOfTextChatsSent > 5 | NumberOfTextChatsSent <= 10 [$__range])) or vector(0)",
     "legendFormat": "6 to 10"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"StageUsage\" | StageName=\"$stage_names\" | NumberOfTextChatsSent > 10 [$__range])) or vector(0)",
     "legendFormat": "11 or more"
    }
   ]
  },
  {
   "title": "Total Memory (MB) in All Stages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 0 | TotalReservedMemoryMb <= 300 [$__range])) or vector(0)",
     "legendFormat": "0 to 300"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 300 | TotalReservedMemoryMb <= 600 [$__range])) or vector(0)",
     "legendFormat": "301 to 600"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 600 | TotalReservedMemoryMb <= 900 [$__range])) or vector(0)",
     "legendFormat": "601 to 900"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 900 | TotalReservedMemoryMb <= 1200 [$__range])) or vector(0)",
     "legendFormat": "901 to 1200"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 1200 | TotalReservedMemoryMb <= 1500 [$__range])) or vector(0)",
     "legendFormat": "1201 to 1500"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 1500 | TotalReservedMemoryMb <= 1800 [$__range])) or vector(0)",
     "legendFormat": "1501 to 1800"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 1800 | TotalReservedMemoryMb <= 2100 [$__range])) or vector(0)",
     "legendFormat": "1801 to 2100"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalReservedMemoryMb > 2100 [$__range])) or vector(0)",
     "legendFormat": "2101 or more"
    }
   ]
  },
  {
   "title": "Used Memory (MB) in All Stages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 0 | TotalAllocatedMemoryMb <= 300 [$__range])) or vector(0)",
     "legendFormat": "0 to 300"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 300 | TotalAllocatedMemoryMb <= 600 [$__range])) or vector(0)",
     "legendFormat": "301 to 600"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 600 | TotalAllocatedMemoryMb <= 900 [$__range])) or vector(0)",
     "legendFormat": "601 to 900"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 900 | TotalAllocatedMemoryMb <= 1200 [$__range])) or vector(0)",
     "legendFormat": "901 to 1200"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 1200 | TotalAllocatedMemoryMb <= 1500 [$__range])) or vector(0)",
     "legendFormat": "1201 to 1500"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 1500 | TotalAllocatedMemoryMb <= 1800 [$__range])) or vector(0)",
     "legendFormat": "1501 to 1800"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 1800 | TotalAllocatedMemoryMb <= 2100 [$__range])) or vector(0)",
     "legendFormat": "1801 to 2100"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | TotalAllocatedMemoryMb > 2100 [$__range])) or vector(0)",
     "legendFormat": "2101 or more"
    }
   ]
  },
  {
   "title": "Total Heap (MB) in All Stages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 0 | MonoHeapSizeMb <= 200 [$__range])) or vector(0)",
     "legendFormat": "0 to 200"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 200 | MonoHeapSizeMb <= 400 [$__range])) or vector(0)",
     "legendFormat": "201 to 400"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 400 | MonoHeapSizeMb <= 600 [$__range])) or vector(0)",
     "legendFormat": "401 to 600"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 600 | MonoHeapSizeMb <= 800 [$__range])) or vector(0)",
     "legendFormat": "601 to 800"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 800 | MonoHeapSizeMb <= 1000 [$__range])) or vector(0)",
     "legendFormat": "801 to 1000"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 1000 | MonoHeapSizeMb <= 1200 [$__range])) or vector(0)",
     "legendFormat": "1001 to 1200"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 1200 | MonoHeapSizeMb <= 1400 [$__range])) or vector(0)",
     "legendFormat": "1201 to 1400"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoHeapSizeMb > 1400 [$__range])) or vector(0)",
     "legendFormat": "1401 or more"
    }
   ]
  },
  {
   "title": "Total Heap (MB) in All Stages",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 0 | MonoUsedSizeMb <= 200 [$__range])) or vector(0)",
     "legendFormat": "0 to 200"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 200 | MonoUsedSizeMb <= 400 [$__range])) or vector(0)",
     "legendFormat": "201 to 400"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 400 | MonoUsedSizeMb <= 600 [$__range])) or vector(0)",
     "legendFormat": "401 to 600"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 600 | MonoUsedSizeMb <= 800 [$__range])) or vector(0)",
     "legendFormat": "601 to 800"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 800 | MonoUsedSizeMb <= 1000 [$__range])) or vector(0)",
     "legendFormat": "801 to 1000"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 1000 | MonoUsedSizeMb <= 1200 [$__range])) or vector(0)",
     "legendFormat": "1001 to 1200"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 1200 | MonoUsedSizeMb <= 1400 [$__range])) or vector(0)",
     "legendFormat": "1201 to 1400"
    },
    {
     "expr": "sum(count_over_time({app=\"Holiday\"} | json | UsageId=\"ResourceUsage\" | MonoUsedSizeMb > 1400 [$__range])) or vector(0)",
     "legendFormat": "1401 or more"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(sum by (ClientId) (count_over_time({app=\"Holiday\"} | json | UsageId=\"ErrorStatus\" [$__range])))",
     "legendFormat": "Number of people for whom an error occurred"
    }
   ]
  },
  {
   "title": "Top 10 Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, sum by (ErrorMessage) (count_over_time({app=\"Holiday\"} | json | UsageId=\"ErrorStatus\" [$__range])))"
    }
   ]
  }
 ]
}